# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 350)
        self.label = QtWidgets.QLabel(parent=MainWindow)
        self.label.setGeometry(QtCore.QRect(280, 5, 175, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=MainWindow)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(30, 280, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.image = QtWidgets.QLabel(parent=MainWindow)
        self.image.setGeometry(QtCore.QRect(235, 60, 450, 275))
        self.image.setText("")
        self.image.setObjectName("image")
        self.radioButton = QtWidgets.QRadioButton(parent=MainWindow)
        self.radioButton.setGeometry(QtCore.QRect(30, 120, 221, 41))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=MainWindow)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 150, 151, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=MainWindow)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 180, 203, 41))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=MainWindow)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 210, 201, 41))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(parent=MainWindow)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 240, 201, 41))
        self.radioButton_5.setObjectName("radioButton_5")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Главное окно"))
        self.label_2.setText(_translate("MainWindow", "Выберите тип функции"))
        self.pushButton.setText(_translate("MainWindow", "Далее ->"))
        self.radioButton.setText(_translate("MainWindow", "Линейная(рис.1)"))
        self.radioButton_2.setText(_translate("MainWindow", "Модуль(рис.2)"))
        self.radioButton_3.setText(_translate("MainWindow", "Корень(рис.3)"))
        self.radioButton_4.setText(_translate("MainWindow", "Дробная(рис.5)"))
        self.radioButton_5.setText(_translate("MainWindow", "Квадратичная(рис.6)"))
